### ISSUE TITLE
Instructions ordering in README

### ISSUE THREAD

**Issue by rahulbhadani** [jmscslgroup/privzone#2]
There is an issue about instruction sequence in README.

Executing 

```{bash}
python manage.py makemigrations
```

gives me the following error:

```
Could not locate SECRET_KEY due to missing config file. Using a fake key because of DEBUG.
No changes detected
```

Should `Create a json file with a key "SECRET_KEY".` go before `makemigration`?

**Comment by rahulbhadani** [comment]
Check further comments on https://github.com/jmscslgroup/privzone/commit/5ff5167f88d40450b80cc4ab1534e181e16bfdd6

**Comment by rpgolota** [comment]
The output is something I added to make sure a secret key is not accidentally forgotten. The secret key is not needed for this step, and just shows up when settings.py is loaded by manage.py, but I see your point.

I'll go ahead and update the readme. I'll also add the example mentioned in #3.
